version: "3.7"
services:
  redis:
    env_file: docker-compose.env
    image: redis:latest
    container_name: superset_cache
    restart: unless-stopped
    volumes:
      - cache_data:/data

  postgres:
    env_file: docker-compose.env
    image: postgres:latest
    container_name: superset_db
    restart: unless-stopped
    volumes:
      - db_data:/var/lib/postgresql/data

  superset:
    env_file: docker-compose.env
    image: apache/superset:latest
    container_name: superset_app
    restart: unless-stopped
    ports:
      - "0.0.0.0:8088:8088"
    depends_on:
      - postgres
      - redis
    volumes:
      - app_data:/app/superset_home

  superset-init:
    env_file: docker-compose.env
    image: apache/superset:latest
    container_name: superset_init
    entrypoint: ["/bin/bash"]
    command: ["/docker-compose-init.sh"]
    user: "root"
    restart: "no"
    depends_on:
      - redis
      - postgres
      - superset
    volumes:
      - ./docker-compose-init.sh:/docker-compose-init.sh

volumes:
  cache_data:
    external: false
  db_data:
    external: false
  app_data:
    external: false